<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class FlightSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('flights')->insert([
            // Chuyến bay cho departure_schedule_id = 1
            [
                'flight_code' => 'VN123',
                'departure_date' => '2024-11-04',
                'departure_time' => '12:00:00',
                'arrival_time' => '13:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'HAN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN124',
                'departure_date' => '2024-11-05',
                'departure_time' => '14:30:00',
                'arrival_time' => '16:00:00',
                'departure_location' => 'HAN',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 2
            [
                'flight_code' => 'VN125',
                'departure_date' => '2024-11-20',
                'departure_time' => '08:00:00',
                'arrival_time' => '09:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'DAD',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN126',
                'departure_date' => '2024-11-21',
                'departure_time' => '17:00:00',
                'arrival_time' => '18:30:00',
                'departure_location' => 'DAD',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 3
            [
                'flight_code' => 'VN127',
                'departure_date' => '2024-11-10',
                'departure_time' => '09:00:00',
                'arrival_time' => '11:00:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'HAN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN128',
                'departure_date' => '2024-11-11',
                'departure_time' => '14:00:00',
                'arrival_time' => '16:00:00',
                'departure_location' => 'HAN',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 4
            [
                'flight_code' => 'VN129',
                'departure_date' => '2024-11-05',
                'departure_time' => '06:00:00',
                'arrival_time' => '08:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'DAD',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN130',
                'departure_date' => '2024-11-06',
                'departure_time' => '18:30:00',
                'arrival_time' => '21:00:00',
                'departure_location' => 'DAD',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 5
            [
                'flight_code' => 'VN131',
                'departure_date' => '2024-11-15',
                'departure_time' => '12:00:00',
                'arrival_time' => '13:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'CXR',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN132',
                'departure_date' => '2024-11-16',
                'departure_time' => '15:00:00',
                'arrival_time' => '16:30:00',
                'departure_location' => 'CXR',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 6
            [
                'flight_code' => 'VN133',
                'departure_date' => '2024-12-20',
                'departure_time' => '09:30:00',
                'arrival_time' => '11:00:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'HAN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN134',
                'departure_date' => '2024-12-21',
                'departure_time' => '15:00:00',
                'arrival_time' => '17:00:00',
                'departure_location' => 'HAN',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 7
            [
                'flight_code' => 'VN135',
                'departure_date' => '2024-11-25',
                'departure_time' => '07:00:00',
                'arrival_time' => '09:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'HAN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN136',
                'departure_date' => '2024-11-26',
                'departure_time' => '18:00:00',
                'arrival_time' => '20:30:00',
                'departure_location' => 'HAN',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 8
            [
                'flight_code' => 'VN137',
                'departure_date' => '2024-11-30',
                'departure_time' => '06:00:00',
                'arrival_time' => '08:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'DAD',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN138',
                'departure_date' => '2024-12-01',
                'departure_time' => '16:00:00',
                'arrival_time' => '18:30:00',
                'departure_location' => 'DAD',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 9
            [
                'flight_code' => 'VN139',
                'departure_date' => '2024-12-15',
                'departure_time' => '11:00:00',
                'arrival_time' => '13:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'CXR',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN140',
                'departure_date' => '2024-12-16',
                'departure_time' => '14:00:00',
                'arrival_time' => '16:30:00',
                'departure_location' => 'CXR',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 10
            [
                'flight_code' => 'VN141',
                'departure_date' => '2024-12-15',
                'departure_time' => '08:00:00',
                'arrival_time' => '10:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'DAD',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN142',
                'departure_date' => '2024-12-16',
                'departure_time' => '20:00:00',
                'arrival_time' => '22:30:00',
                'departure_location' => 'DAD',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 11
            [
                'flight_code' => 'VN143',
                'departure_date' => '2024-12-15',
                'departure_time' => '09:30:00',
                'arrival_time' => '11:00:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'HAN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN144',
                'departure_date' => '2024-12-16',
                'departure_time' => '15:00:00',
                'arrival_time' => '17:30:00',
                'departure_location' => 'HAN',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 11,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 12
            [
                'flight_code' => 'VN145',
                'departure_date' => '2024-12-20',
                'departure_time' => '10:00:00',
                'arrival_time' => '12:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'DAD',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN146',
                'departure_date' => '2024-12-21',
                'departure_time' => '17:00:00',
                'arrival_time' => '19:30:00',
                'departure_location' => 'DAD',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 12,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 13
            [
                'flight_code' => 'VN147',
                'departure_date' => '2024-11-25',
                'departure_time' => '08:00:00',
                'arrival_time' => '09:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'HUI',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN148',
                'departure_date' => '2024-11-26',
                'departure_time' => '19:00:00',
                'arrival_time' => '20:30:00',
                'departure_location' => 'HUI',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 13,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 14
            [
                'flight_code' => 'VN149',
                'departure_date' => '2024-11-30',
                'departure_time' => '09:00:00',
                'arrival_time' => '11:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'NHA',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN150',
                'departure_date' => '2024-12-01',
                'departure_time' => '14:00:00',
                'arrival_time' => '16:30:00',
                'departure_location' => 'NHA',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 14,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 15
            [
                'flight_code' => 'VN151',
                'departure_date' => '2024-11-15',
                'departure_time' => '15:00:00',
                'arrival_time' => '17:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'PHU',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN152',
                'departure_date' => '2024-11-16',
                'departure_time' => '13:00:00',
                'arrival_time' => '15:30:00',
                'departure_location' => 'PHU',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 15,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 16
            [
                'flight_code' => 'VN155',
                'departure_date' => '2024-12-10',
                'departure_time' => '08:00:00',
                'arrival_time' => '09:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'DAD',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 16,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN156',
                'departure_date' => '2024-12-11',
                'departure_time' => '17:00:00',
                'arrival_time' => '18:30:00',
                'departure_location' => 'DAD',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 16,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 17
            [
                'flight_code' => 'VN157',
                'departure_date' => '2024-12-15',
                'departure_time' => '12:00:00',
                'arrival_time' => '13:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'HAN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN158',
                'departure_date' => '2024-12-16',
                'departure_time' => '14:30:00',
                'arrival_time' => '16:00:00',
                'departure_location' => 'HAN',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 17,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 18
            [
                'flight_code' => 'VN159',
                'departure_date' => '2024-12-20',
                'departure_time' => '10:00:00',
                'arrival_time' => '11:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'NHA',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN160',
                'departure_date' => '2024-12-21',
                'departure_time' => '15:00:00',
                'arrival_time' => '16:30:00',
                'departure_location' => 'NHA',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 19
            [
                'flight_code' => 'VN161',
                'departure_date' => '2024-12-25',
                'departure_time' => '09:00:00',
                'arrival_time' => '10:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'PHU',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 19,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN162',
                'departure_date' => '2024-12-26',
                'departure_time' => '16:00:00',
                'arrival_time' => '17:30:00',
                'departure_location' => 'PHU',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 19,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 20
            [
                'flight_code' => 'VN163',
                'departure_date' => '2025-01-01',
                'departure_time' => '11:30:00',
                'arrival_time' => '13:00:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'BKK',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 20,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN164',
                'departure_date' => '2025-01-02',
                'departure_time' => '14:30:00',
                'arrival_time' => '16:00:00',
                'departure_location' => 'BKK',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 20,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 21
            [
                'flight_code' => 'VN165',
                'departure_date' => '2025-01-10',
                'departure_time' => '12:00:00',
                'arrival_time' => '14:00:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'HUI',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN166',
                'departure_date' => '2025-01-11',
                'departure_time' => '16:00:00',
                'arrival_time' => '18:00:00',
                'departure_location' => 'HUI',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 21,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 22
            [
                'flight_code' => 'VN167',
                'departure_date' => '2025-01-15',
                'departure_time' => '10:30:00',
                'arrival_time' => '12:00:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'DAD',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN168',
                'departure_date' => '2025-01-16',
                'departure_time' => '14:00:00',
                'arrival_time' => '15:30:00',
                'departure_location' => 'DAD',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 22,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 23
            [
                'flight_code' => 'VN169',
                'departure_date' => '2025-01-20',
                'departure_time' => '12:00:00',
                'arrival_time' => '14:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'NHA',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN170',
                'departure_date' => '2025-01-21',
                'departure_time' => '15:00:00',
                'arrival_time' => '17:00:00',
                'departure_location' => 'NHA',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 23,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 24
            [
                'flight_code' => 'VN171',
                'departure_date' => '2025-01-25',
                'departure_time' => '10:00:00',
                'arrival_time' => '11:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'PHU',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN172',
                'departure_date' => '2025-01-26',
                'departure_time' => '16:00:00',
                'arrival_time' => '17:30:00',
                'departure_location' => 'PHU',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 24,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 25
            [
                'flight_code' => 'VN173',
                'departure_date' => '2025-01-30',
                'departure_time' => '11:00:00',
                'arrival_time' => '12:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'BKK',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN174',
                'departure_date' => '2025-01-31',
                'departure_time' => '15:00:00',
                'arrival_time' => '16:30:00',
                'departure_location' => 'BKK',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 25,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 26
            [
                'flight_code' => 'VN175',
                'departure_date' => '2025-02-05',
                'departure_time' => '09:00:00',
                'arrival_time' => '10:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'HUI',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN176',
                'departure_date' => '2025-02-06',
                'departure_time' => '18:00:00',
                'arrival_time' => '19:30:00',
                'departure_location' => 'HUI',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 26,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 27
            [
                'flight_code' => 'VN177',
                'departure_date' => '2025-02-10',
                'departure_time' => '10:00:00',
                'arrival_time' => '11:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'DAD',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN178',
                'departure_date' => '2025-02-11',
                'departure_time' => '15:00:00',
                'arrival_time' => '16:30:00',
                'departure_location' => 'DAD',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 27,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 28
            [
                'flight_code' => 'VN179',
                'departure_date' => '2025-02-15',
                'departure_time' => '12:00:00',
                'arrival_time' => '13:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'PHU',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN180',
                'departure_date' => '2025-02-16',
                'departure_time' => '16:30:00',
                'arrival_time' => '18:00:00',
                'departure_location' => 'PHU',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 28,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 29
            [
                'flight_code' => 'VN181',
                'departure_date' => '2025-02-20',
                'departure_time' => '10:00:00',
                'arrival_time' => '11:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'NHA',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 29,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN182',
                'departure_date' => '2025-02-21',
                'departure_time' => '15:00:00',
                'arrival_time' => '16:30:00',
                'departure_location' => 'NHA',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 29,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Chuyến bay cho departure_schedule_id = 30
            [
                'flight_code' => 'VN183',
                'departure_date' => '2025-03-01',
                'departure_time' => '09:00:00',
                'arrival_time' => '10:30:00',
                'departure_location' => 'SGN',
                'arrival_location' => 'VIE',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'one_way',
                'departure_schedule_id' => 30,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'flight_code' => 'VN184',
                'departure_date' => '2025-03-02',
                'departure_time' => '16:00:00',
                'arrival_time' => '17:30:00',
                'departure_location' => 'VIE',
                'arrival_location' => 'SGN',
                'airline' => 'Vietnam Airlines',
                'flight_type' => 'round_trip',
                'departure_schedule_id' => 30,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
