<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class TourSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tour')->insert([
            [
                'name' => 'Tour Việt nam - Hà Nội',
                'slug' => Str::slug('Tour Việt nam - Hà Nội'),
                'id_destination' => 1,
                'description' => 'Hà Nội, thủ đô của Việt Nam, nổi tiếng với kiến trúc trăm tuổi và nền văn hóa phong phú với sự ảnh hưởng của khu vực Đông Nam Á, Trung Quốc và Pháp. Trung tâm thành phố là Khu phố cổ nhộn nhịp, nơi các con phố hẹp được mang tên "hàng".',
                'price' => 1500000,
                'price_single_room' => 1500000,
                'number_days' => 3,
                'image_main' => 'vietnam-hanoi.jpg',
                'program_code' => 'THH01',
                'id_departure_location' => 1,
                'person' => 2,
            ],
            [
                'name' => 'Tour Thái Lan - Bangkok',
                'slug' => Str::slug('Tour Thái Lan - Bangkok'),
                'id_destination' => 2,
                'description' => 'Khám phá thủ đô Bangkok với nhiều điểm tham quan nổi tiếng.',
                'price' => 1800000,
                'price_single_room' => 1500000,
                'number_days' => 4,
                'image_main' => 'thailand-bangkok.jpg',
                'program_code' => 'TT01',
                'id_departure_location' => 2,
                'person' => 3,
            ],
            [
                'name' => 'Tour Nhật Bản - Tokyo',
                'slug' => Str::slug('Tour Nhật Bản - Tokyo'),
                'id_destination' => 3,
                'description' => 'Trải nghiệm văn hóa Nhật Bản tại Tokyo.',
                'price' => 2000000,
                'price_single_room' => 2900000,
                'number_days' => 5,
                'image_main' => 'japan-tokyo.jpg',
                'program_code' => 'TJP01',
                'id_departure_location' => 1,
                'person' => 4,
            ],
            [
                'name' => 'Tour Hàn Quốc - Seoul',
                'slug' => Str::slug('Tour Hàn Quốc - Seoul'),
                'id_destination' => 4,
                'description' => 'Khám phá các địa điểm nổi tiếng tại Seoul.',
                'price' => 2500000,
                'price_single_room' => 1500000,
                'number_days' => 5,
                'image_main' => 'korea-seoul.jpg',
                'program_code' => 'THK01',
                'id_departure_location' => 1,
                'person' => 3,
            ],
            [
                'name' => 'Tour Mỹ - New York',
                'slug' => Str::slug('Tour Mỹ - New York'),
                'id_destination' => 5,
                'description' => 'Khám phá thành phố không bao giờ ngủ New York.',
                'price' => 3000000,
                'price_single_room' => 2900000,
                'number_days' => 6,
                'image_main' => 'usa-new-york.jpg',
                'program_code' => 'TNY01',
                'id_departure_location' => 1,
                'person' => 4,
            ],
            [
                'name' => 'Tour Anh - London',
                'slug' => Str::slug('Tour Anh - London'),
                'id_destination' => 6,
                'description' => 'Tham quan thành phố London với các biểu tượng nổi tiếng.',
                'price' => 2800000,
                'price_single_room' => 1500000,
                'number_days' => 5,
                'image_main' => 'uk-london.jpg',
                'program_code' => 'TUL01',
                'id_departure_location' => 1,
                'person' => 3,
            ],
            [
                'name' => 'Tour Pháp - Paris',
                'slug' => Str::slug('Tour Pháp - Paris'),
                'id_destination' => 7,
                'description' => 'Tham quan thủ đô ánh sáng Paris.',
                'price' => 3500000,
                'price_single_room' => 2900000,
                'number_days' => 5,
                'image_main' => 'france-paris.jpg',
                'program_code' => 'TPA01',
                'id_departure_location' => 1,
                'person' => 3,
            ],
            [
                'name' => 'Tour Úc - Sydney',
                'slug' => Str::slug('Tour Úc - Sydney'),
                'id_destination' => 8,
                'description' => 'Khám phá vẻ đẹp của Sydney, thành phố ven biển tuyệt đẹp.',
                'price' => 4000000,
                'price_single_room' => 1500000,
                'number_days' => 7,
                'image_main' => 'australia-sydney.jpg',
                'program_code' => 'TAU01',
                'id_departure_location' => 2,
                'person' => 2,
            ],
            [
                'name' => 'Tour Canada - Toronto',
                'slug' => Str::slug('Tour Canada - Toronto'),
                'id_destination' => 9,
                'description' => 'Tham quan thành phố Toronto với các điểm tham quan thú vị.',
                'price' => 3000000,
                'price_single_room' => 2900000,
                'number_days' => 5,
                'image_main' => 'canada-toronto.jpg',
                'program_code' => 'TCT01',
                'id_departure_location' => 3,
                'person' => 3,
            ],
            [
                'name' => 'Tour Ấn Độ - Delhi',
                'slug' => Str::slug('Tour Ấn Độ - Delhi'),
                'id_destination' => 10,
                'description' => 'Khám phá vẻ đẹp của thủ đô Ấn Độ, Delhi.',
                'price' => 2000000,
                'price_single_room' => 1500000,
                'number_days' => 4,
                'image_main' => 'india-delhi.jpg',
                'program_code' => 'TID01',
                'id_departure_location' => 2,
                'person' => 4,
            ],
            [
                'name' => 'Tour Malaysia - Kuala Lumpur',
                'slug' => Str::slug('Tour Malaysia - Kuala Lumpur'),
                'id_destination' => 11,
                'description' => 'Khám phá Kuala Lumpur với những công trình kiến trúc hiện đại.',
                'price' => 2200000,
                'price_single_room' => 2900000,
                'number_days' => 4,
                'image_main' => 'malaysia-kuala-lumpur.jpg',
                'program_code' => 'TML01',
                'id_departure_location' => 2,
                'person' => 3,
            ],
            [
                'name' => 'Tour Singapore - Marina Bay',
                'slug' => Str::slug('Tour Singapore - Marina Bay'),
                'id_destination' => 12,
                'description' => 'Trải nghiệm cuộc sống sôi động tại Singapore.',
                'price' => 2500000,
                'price_single_room' => 1500000,
                'number_days' => 3,
                'image_main' => 'singapore-marina-bay.jpg',
                'program_code' => 'TSG01',
                'id_departure_location' => 3,
                'person' => 2,
            ],
            [
                'name' => 'Tour Tây Ban Nha - Barcelona',
                'slug' => Str::slug('Tour Tây Ban Nha - Barcelona'),
                'id_destination' => 13,
                'description' => 'Khám phá thành phố Barcelona với những nét đẹp văn hóa đặc sắc.',
                'price' => 2700000,
                'price_single_room' => 2900000,
                'number_days' => 6,
                'image_main' => 'spain-barcelona.jpg',
                'program_code' => 'TSB01',
                'id_departure_location' => 1,
                'person' => 3,
            ],
            [
                'name' => 'Tour Ý - Rome',
                'slug' => Str::slug('Tour Ý - Rome'),
                'id_destination' => 14,
                'description' => 'Tham quan thành phố Rome, nơi có nhiều di sản văn hóa.',
                'price' => 3500000,
                'price_single_room' => 1500000,
                'number_days' => 5,
                'image_main' => 'italy-rome.jpg',
                'program_code' => 'TIR01',
                'id_departure_location' => 1,
                'person' => 3,
            ],
            [
                'name' => 'Tour Đức - Berlin',
                'slug' => Str::slug('Tour Đức - Berlin'),
                'id_destination' => 15,
                'description' => 'Khám phá Berlin với các biểu tượng nổi tiếng.',
                'price' => 3000000,
                'price_single_room' => 2900000,
                'number_days' => 5,
                'image_main' => 'germany-berlin.jpg',
                'program_code' => 'TDE01',
                'id_departure_location' => 1,
                'person' => 3,
            ],
        ]);
    }
}
